2025-03-27 02:24:52,554 - ERROR - Failed to create user {'name': 'Alice', 'email': 'alice@example.com', 'role': 'admin'}: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/create_user (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AA9C827D40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-27 02:24:56,643 - ERROR - Failed to create user {'name': 'Alice', 'email': 'alice@example.com', 'role': 'admin'}: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/create_user (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AA9CB71010>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-27 02:25:00,737 - ERROR - Failed to create user {'name': 'Alice', 'email': 'alice@example.com', 'role': 'admin'}: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/create_user (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AA9CB71700>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-27 02:25:00,737 - ERROR - Failed to create user {'name': 'Alice', 'email': 'alice@example.com', 'role': 'admin'} after 3 attempts.
2025-03-27 02:25:04,823 - ERROR - Failed to create user {'name': 'Charlie', 'email': 'charlie@example.com', 'role': 'moderator'}: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/create_user (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AA9CB71E20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-27 02:25:08,898 - ERROR - Failed to create user {'name': 'Charlie', 'email': 'charlie@example.com', 'role': 'moderator'}: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/create_user (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AA9CB72510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
